# bundle exec jekyll serve --host=0.0.0.0

title: MycilaTrial
description: Arduino / ESP32 library to add a trial duration in your app
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
